/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimesheetsRouteImport } from './routes/timesheets'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SupplyOrdersRouteImport } from './routes/supply-orders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesPipelineRouteImport } from './routes/sales-pipeline'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReferAndEarnRouteImport } from './routes/refer-and-earn'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as MapRouteImport } from './routes/map'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as JobsPipelineRouteImport } from './routes/jobs-pipeline'
import { Route as JobFormsRouteImport } from './routes/job-forms'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InstallationsRouteImport } from './routes/installations'
import { Route as ImportCustomersRouteImport } from './routes/import-customers'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ClientHubRouteImport } from './routes/client-hub'
import { Route as ChemicalsRouteImport } from './routes/chemicals'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicianIndexRouteImport } from './routes/technician.index'
import { Route as ImportCustomersManualRouteImport } from './routes/import-customers.manual'
import { Route as ImportCustomersCsvRouteImport } from './routes/import-customers.csv'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as TechnicianJobIdRouteImport } from './routes/technician.job.$id'

const TimesheetsRoute = TimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyOrdersRoute = SupplyOrdersRouteImport.update({
  id: '/supply-orders',
  path: '/supply-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPipelineRoute = SalesPipelineRouteImport.update({
  id: '/sales-pipeline',
  path: '/sales-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferAndEarnRoute = ReferAndEarnRouteImport.update({
  id: '/refer-and-earn',
  path: '/refer-and-earn',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsPipelineRoute = JobsPipelineRouteImport.update({
  id: '/jobs-pipeline',
  path: '/jobs-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const JobFormsRoute = JobFormsRouteImport.update({
  id: '/job-forms',
  path: '/job-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsRoute = InstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportCustomersRoute = ImportCustomersRouteImport.update({
  id: '/import-customers',
  path: '/import-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHubRoute = ClientHubRouteImport.update({
  id: '/client-hub',
  path: '/client-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ChemicalsRoute = ChemicalsRouteImport.update({
  id: '/chemicals',
  path: '/chemicals',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/technician/',
  path: '/technician/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportCustomersManualRoute = ImportCustomersManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => ImportCustomersRoute,
} as any)
const ImportCustomersCsvRoute = ImportCustomersCsvRouteImport.update({
  id: '/csv',
  path: '/csv',
  getParentRoute: () => ImportCustomersRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const TechnicianJobIdRoute = TechnicianJobIdRouteImport.update({
  id: '/technician/job/$id',
  path: '/technician/job/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/chemicals': typeof ChemicalsRoute
  '/client-hub': typeof ClientHubRoute
  '/customers': typeof CustomersRouteWithChildren
  '/equipment': typeof EquipmentRoute
  '/expenses': typeof ExpensesRoute
  '/import-customers': typeof ImportCustomersRouteWithChildren
  '/installations': typeof InstallationsRoute
  '/invoices': typeof InvoicesRoute
  '/job-forms': typeof JobFormsRoute
  '/jobs-pipeline': typeof JobsPipelineRoute
  '/leads': typeof LeadsRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/marketing': typeof MarketingRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/quotes': typeof QuotesRoute
  '/receptionist': typeof ReceptionistRoute
  '/refer-and-earn': typeof ReferAndEarnRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/sales-pipeline': typeof SalesPipelineRoute
  '/settings': typeof SettingsRoute
  '/supply-orders': typeof SupplyOrdersRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timesheets': typeof TimesheetsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/import-customers/csv': typeof ImportCustomersCsvRoute
  '/import-customers/manual': typeof ImportCustomersManualRoute
  '/technician/': typeof TechnicianIndexRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/chemicals': typeof ChemicalsRoute
  '/client-hub': typeof ClientHubRoute
  '/customers': typeof CustomersRouteWithChildren
  '/equipment': typeof EquipmentRoute
  '/expenses': typeof ExpensesRoute
  '/import-customers': typeof ImportCustomersRouteWithChildren
  '/installations': typeof InstallationsRoute
  '/invoices': typeof InvoicesRoute
  '/job-forms': typeof JobFormsRoute
  '/jobs-pipeline': typeof JobsPipelineRoute
  '/leads': typeof LeadsRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/marketing': typeof MarketingRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/quotes': typeof QuotesRoute
  '/receptionist': typeof ReceptionistRoute
  '/refer-and-earn': typeof ReferAndEarnRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/sales-pipeline': typeof SalesPipelineRoute
  '/settings': typeof SettingsRoute
  '/supply-orders': typeof SupplyOrdersRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timesheets': typeof TimesheetsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/import-customers/csv': typeof ImportCustomersCsvRoute
  '/import-customers/manual': typeof ImportCustomersManualRoute
  '/technician': typeof TechnicianIndexRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/calendar': typeof CalendarRoute
  '/chemicals': typeof ChemicalsRoute
  '/client-hub': typeof ClientHubRoute
  '/customers': typeof CustomersRouteWithChildren
  '/equipment': typeof EquipmentRoute
  '/expenses': typeof ExpensesRoute
  '/import-customers': typeof ImportCustomersRouteWithChildren
  '/installations': typeof InstallationsRoute
  '/invoices': typeof InvoicesRoute
  '/job-forms': typeof JobFormsRoute
  '/jobs-pipeline': typeof JobsPipelineRoute
  '/leads': typeof LeadsRoute
  '/maintenance': typeof MaintenanceRoute
  '/map': typeof MapRoute
  '/marketing': typeof MarketingRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/quotes': typeof QuotesRoute
  '/receptionist': typeof ReceptionistRoute
  '/refer-and-earn': typeof ReferAndEarnRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/sales-pipeline': typeof SalesPipelineRoute
  '/settings': typeof SettingsRoute
  '/supply-orders': typeof SupplyOrdersRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/timesheets': typeof TimesheetsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/import-customers/csv': typeof ImportCustomersCsvRoute
  '/import-customers/manual': typeof ImportCustomersManualRoute
  '/technician/': typeof TechnicianIndexRoute
  '/technician/job/$id': typeof TechnicianJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/auth'
    | '/automations'
    | '/calendar'
    | '/chemicals'
    | '/client-hub'
    | '/customers'
    | '/equipment'
    | '/expenses'
    | '/import-customers'
    | '/installations'
    | '/invoices'
    | '/job-forms'
    | '/jobs-pipeline'
    | '/leads'
    | '/maintenance'
    | '/map'
    | '/marketing'
    | '/messages'
    | '/payments'
    | '/quotes'
    | '/receptionist'
    | '/refer-and-earn'
    | '/reports'
    | '/requests'
    | '/sales-pipeline'
    | '/settings'
    | '/supply-orders'
    | '/tasks'
    | '/team'
    | '/timesheets'
    | '/customers/$id'
    | '/import-customers/csv'
    | '/import-customers/manual'
    | '/technician/'
    | '/technician/job/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/auth'
    | '/automations'
    | '/calendar'
    | '/chemicals'
    | '/client-hub'
    | '/customers'
    | '/equipment'
    | '/expenses'
    | '/import-customers'
    | '/installations'
    | '/invoices'
    | '/job-forms'
    | '/jobs-pipeline'
    | '/leads'
    | '/maintenance'
    | '/map'
    | '/marketing'
    | '/messages'
    | '/payments'
    | '/quotes'
    | '/receptionist'
    | '/refer-and-earn'
    | '/reports'
    | '/requests'
    | '/sales-pipeline'
    | '/settings'
    | '/supply-orders'
    | '/tasks'
    | '/team'
    | '/timesheets'
    | '/customers/$id'
    | '/import-customers/csv'
    | '/import-customers/manual'
    | '/technician'
    | '/technician/job/$id'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/auth'
    | '/automations'
    | '/calendar'
    | '/chemicals'
    | '/client-hub'
    | '/customers'
    | '/equipment'
    | '/expenses'
    | '/import-customers'
    | '/installations'
    | '/invoices'
    | '/job-forms'
    | '/jobs-pipeline'
    | '/leads'
    | '/maintenance'
    | '/map'
    | '/marketing'
    | '/messages'
    | '/payments'
    | '/quotes'
    | '/receptionist'
    | '/refer-and-earn'
    | '/reports'
    | '/requests'
    | '/sales-pipeline'
    | '/settings'
    | '/supply-orders'
    | '/tasks'
    | '/team'
    | '/timesheets'
    | '/customers/$id'
    | '/import-customers/csv'
    | '/import-customers/manual'
    | '/technician/'
    | '/technician/job/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  AuthRoute: typeof AuthRoute
  AutomationsRoute: typeof AutomationsRoute
  CalendarRoute: typeof CalendarRoute
  ChemicalsRoute: typeof ChemicalsRoute
  ClientHubRoute: typeof ClientHubRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  EquipmentRoute: typeof EquipmentRoute
  ExpensesRoute: typeof ExpensesRoute
  ImportCustomersRoute: typeof ImportCustomersRouteWithChildren
  InstallationsRoute: typeof InstallationsRoute
  InvoicesRoute: typeof InvoicesRoute
  JobFormsRoute: typeof JobFormsRoute
  JobsPipelineRoute: typeof JobsPipelineRoute
  LeadsRoute: typeof LeadsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MapRoute: typeof MapRoute
  MarketingRoute: typeof MarketingRoute
  MessagesRoute: typeof MessagesRoute
  PaymentsRoute: typeof PaymentsRoute
  QuotesRoute: typeof QuotesRoute
  ReceptionistRoute: typeof ReceptionistRoute
  ReferAndEarnRoute: typeof ReferAndEarnRoute
  ReportsRoute: typeof ReportsRoute
  RequestsRoute: typeof RequestsRoute
  SalesPipelineRoute: typeof SalesPipelineRoute
  SettingsRoute: typeof SettingsRoute
  SupplyOrdersRoute: typeof SupplyOrdersRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  TimesheetsRoute: typeof TimesheetsRoute
  TechnicianIndexRoute: typeof TechnicianIndexRoute
  TechnicianJobIdRoute: typeof TechnicianJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timesheets': {
      id: '/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof TimesheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-orders': {
      id: '/supply-orders'
      path: '/supply-orders'
      fullPath: '/supply-orders'
      preLoaderRoute: typeof SupplyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-pipeline': {
      id: '/sales-pipeline'
      path: '/sales-pipeline'
      fullPath: '/sales-pipeline'
      preLoaderRoute: typeof SalesPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer-and-earn': {
      id: '/refer-and-earn'
      path: '/refer-and-earn'
      fullPath: '/refer-and-earn'
      preLoaderRoute: typeof ReferAndEarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs-pipeline': {
      id: '/jobs-pipeline'
      path: '/jobs-pipeline'
      fullPath: '/jobs-pipeline'
      preLoaderRoute: typeof JobsPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-forms': {
      id: '/job-forms'
      path: '/job-forms'
      fullPath: '/job-forms'
      preLoaderRoute: typeof JobFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations': {
      id: '/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof InstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-customers': {
      id: '/import-customers'
      path: '/import-customers'
      fullPath: '/import-customers'
      preLoaderRoute: typeof ImportCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-hub': {
      id: '/client-hub'
      path: '/client-hub'
      fullPath: '/client-hub'
      preLoaderRoute: typeof ClientHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chemicals': {
      id: '/chemicals'
      path: '/chemicals'
      fullPath: '/chemicals'
      preLoaderRoute: typeof ChemicalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/': {
      id: '/technician/'
      path: '/technician'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-customers/manual': {
      id: '/import-customers/manual'
      path: '/manual'
      fullPath: '/import-customers/manual'
      preLoaderRoute: typeof ImportCustomersManualRouteImport
      parentRoute: typeof ImportCustomersRoute
    }
    '/import-customers/csv': {
      id: '/import-customers/csv'
      path: '/csv'
      fullPath: '/import-customers/csv'
      preLoaderRoute: typeof ImportCustomersCsvRouteImport
      parentRoute: typeof ImportCustomersRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/technician/job/$id': {
      id: '/technician/job/$id'
      path: '/technician/job/$id'
      fullPath: '/technician/job/$id'
      preLoaderRoute: typeof TechnicianJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface ImportCustomersRouteChildren {
  ImportCustomersCsvRoute: typeof ImportCustomersCsvRoute
  ImportCustomersManualRoute: typeof ImportCustomersManualRoute
}

const ImportCustomersRouteChildren: ImportCustomersRouteChildren = {
  ImportCustomersCsvRoute: ImportCustomersCsvRoute,
  ImportCustomersManualRoute: ImportCustomersManualRoute,
}

const ImportCustomersRouteWithChildren = ImportCustomersRoute._addFileChildren(
  ImportCustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  AuthRoute: AuthRoute,
  AutomationsRoute: AutomationsRoute,
  CalendarRoute: CalendarRoute,
  ChemicalsRoute: ChemicalsRoute,
  ClientHubRoute: ClientHubRoute,
  CustomersRoute: CustomersRouteWithChildren,
  EquipmentRoute: EquipmentRoute,
  ExpensesRoute: ExpensesRoute,
  ImportCustomersRoute: ImportCustomersRouteWithChildren,
  InstallationsRoute: InstallationsRoute,
  InvoicesRoute: InvoicesRoute,
  JobFormsRoute: JobFormsRoute,
  JobsPipelineRoute: JobsPipelineRoute,
  LeadsRoute: LeadsRoute,
  MaintenanceRoute: MaintenanceRoute,
  MapRoute: MapRoute,
  MarketingRoute: MarketingRoute,
  MessagesRoute: MessagesRoute,
  PaymentsRoute: PaymentsRoute,
  QuotesRoute: QuotesRoute,
  ReceptionistRoute: ReceptionistRoute,
  ReferAndEarnRoute: ReferAndEarnRoute,
  ReportsRoute: ReportsRoute,
  RequestsRoute: RequestsRoute,
  SalesPipelineRoute: SalesPipelineRoute,
  SettingsRoute: SettingsRoute,
  SupplyOrdersRoute: SupplyOrdersRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  TimesheetsRoute: TimesheetsRoute,
  TechnicianIndexRoute: TechnicianIndexRoute,
  TechnicianJobIdRoute: TechnicianJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
